### PR TITLE
Made compatible and tested with Symfony 4.0

### PR DESCRIPTION
**Pull request by TheDevilOnLine**
I've updated the composer json to match the requirements for Symfony 4.0 and ran PHPunit to verify it passes the tests. Please be so kind to merge my change and create a new tag (I'd suggest bumping to 2.0 since the minimal PHP version is also updated).

### CODE REVIEW

**Comment by Mika56** [comment]
Hi,

It seems to me that we can allow Symfony 4 while keeping old PHP 5 compatibility:
* Update the composer.json to revert the minimum PHP version. Each environnement will install either version 2, 3 or 4 of `symfony/http-foundation` depending on available PHP version and already installed symfony/http-foundation package.
* Remove the composer.lock file so every tested version will resolve it's own compatible version of symfony/http-foundation
* Update `.travis.yml` so composer command is `update` instead of `install` (line 23)

Tests should then work on every version.

**Comment by TheDevilOnLine** [comment]
The only way to do that (as far as I'm aware) is to remove the min php requirement, as it overwrites the actual PHP version for Composer. Therefore I couldn't install Symfony 4, unless I up'ed (or removed) the config.platform.php setting.

**Comment by Mika56** [comment]
Hum, I wonder why that platform requirement is there. I remember putting it for a reason, but if all tests pass without it that's good to me

**Comment by TheDevilOnLine** [comment]
I've updated the PR to remove the composer.json and the PHP platform config

**Comment by Mika56** [comment]
I somehow has completely missed that you updated your PR as I had requested.
Merging now, I'll publish a new release later tonight

**Pull request merged**
