### PR TITLE
Count MX lookup requests as per RFC

### LINKED ISSUE #25: MX record lookups not counted according to RFC 7208
RFC 7208 says:

>  When evaluating the "mx" mechanism, the number of "MX" resource records queried is included in the overall limit of 10 mechanisms/modifiers that cause DNS lookups as described above.

But `countRequest()` is only called once, when the MX records are looked up (but not for each record returned that causes an A lookup)

https://github.com/Mika56/PHP-SPF-Check/blob/d5b0aa4fe98577751ccab9e6085f73bd28eccb75/src/SPFCheck.php#L243-L248

There is a check that there isn't more than 10 MX records returned, which matches the following sentence in the RFC ("In addition to that limit, the evaluation of each "MX" record MUST NOT result inmquerying more than 10 address records"), but the lookup of an MX record seems to only count for one DNS request in total (as far as `countRequest()` goes).

An example of a SPF record that is accepted that should not be is something like:

`v=spf1 mx include:foo.example.com include:bar.example.com`

with *nine* MX records attached to the same domain (should be over the limit as defined in the RFC, as it causes 11 DNS lookups, but this library will only count 3 - before includes are evaluated further).

### PR DESCRIPTION
**Pull request by dominics**
Fixes #25

### CODE REVIEW

**Comment by dominics** [comment]
Found it a bit hard to interpret the `mech-at-limit` and `mech-over-limit` cases for the RFC tests. They seem to expect this to pass:

```
  e6.example.com:
    - SPF: v=spf1 a mx a mx a mx a mx a ptr ip4:1.2.3.4 -all
    - A: 1.2.3.8
    - MX: [10, e6.example.com]
```

But according to RFC 7208, the MX lookup of the A of e6.example.com should be counted toward the number of mechanisms. (My reading of this case is as 11 lookups not 10, so I wouldn't expect a pass).

Not counting the *first* A lookup caused by the MX records returned seems to match what they expect. But it's weird.

**Comment by Mika56** [comment]
Hi and thanks for catching that bug. I'm quite astonished that the official test suite does not contain a test that would check this sentence, but I understand it as you do.
I don't understand what the `$skip` variable is for in your commit? If I read it correctly, it skips the first lookup from being counted? Shouldn't the first lookup be counted too?

**Comment by dominics** [comment]
> Shouldn't the first lookup be counted too?

Yeah, I'd expect so. But that causes the `mech-at-limit` test case in the RFC 7208 test to fail (it has ten DNS-causing mechanisms, but also an MX record that needs to be looked up - so my reading is that it should be 11 lookups and fail, but the case expects a pass)

**Comment by Mika56** [comment]
So, I went to read RFC 7208 again and oh boy it's hard to understand.

So I went to see another source that we should be able to trust, pyspf. It is used by postfix's de-facto SPF checker.
From what I understand, in https://github.com/sdgathman/pyspf/blob/master/spf.py#L1288 they have multiple counters: a maximum of 10 lookups made directly from mechanisms, a maximum of 10 lookups for MX lookups, a maximum of 10 lookups for PTR and another 10 maximum for CNAME.
If I'm right, that would mean that for the following domain:
```
 e6.example.com:
    - SPF: v=spf1 a mx a mx a mx a mx a ptr ip4:1.2.3.4 -all
    - A: 1.2.3.8
    - MX: [10, e6.example.com]
```
DNS lookups from mechanisms would be 10: 5 times an `a`, 4 times a `mx` and one `ptr`.
MX limit is only at 4, because only one MX record is returned by the `mx` mechanism

```
 e6.example.com:
    - SPF: v=spf1 a mx a mx a mx a mx a ptr ip4:1.2.3.4 -all
    - A: 1.2.3.8
    - MX: [10, e6.example.com]
    - MX: [11, e7.example.com]
```
Would still be 10 DNS lookups, but we now have 8 MX lookups: each `mx` mechanism looked up two names.

Does that seem right to you?

**Comment by Mika56** [comment]
Closing this as this will be fixed in #28

**Pull request closed without merging**
