### PR TITLE
Use PHP DNS Direct Query Module instead of php dns_get_record() to specify the nameserver to use for the query.

### PR DESCRIPTION
**Pull request by btafoya**
Added PHP DNS Direct Query Module (https://github.com/purplepixie/phpdns) to add the ability to specify the nameserver to query for the results.

### CODE REVIEW

**Comment by btafoya** [comment]
Fixed a typo created the phpstorm.

**Comment by Mika56** [comment]
Hi,

This looks good to me. However, can you make your code into another class implementing `DNSRecordGetterInterface`? This is also why the tests are failing.

**Comment by btafoya** [comment]
Sure thing!

**Comment by btafoya** [comment]
OK, created a separate getter class and added a unit test and changed the readme to reflect the use of the new class. Not sure why it is failing under php 7+.

**Comment by Mika56** [comment]
Okay, so, it took me a while, but I can confirm PHP7+ failing is not your fault.
For some reason, Travis was now building when I push directly into master, so I didn't catch an error I introduced at some point (well, I should not be pushing into master anyway).

I don't have the time to check what exactly is going wrong, but I'll look at it tomorrow. Once this is fixed I'll rebase and merge, so I can publish a new version on Composer.

**Comment by Mika56** [comment]
Hi,

I'm updating a bit your code, and intent to squash it before merging. Can you please [allow me to push to your fork](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by btafoya** [comment]
Done!

**Comment by Mika56** [comment]
I'm not sure exactly how Travis works. I had to update the .travis.yml file, but it doesn't seem to be reading the file from the branch, but from master instead, so tests are failing.
I'm merging to see if this makes Travis read the new .travis.yml. In all cases, I'll publish a new version once Travis reports ok

**Comment by Mika56** [comment]
Yup, that's what I thought, Travis was not using the branch's .travis.yml
I've just published version 1.1.0

**Pull request merged**
